# Generated by Django 4.1.1 on 2022-11-06 20:15

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_article_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
