# Generated by Django 4.1.1 on 2022-11-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie1',
            field=models.CharField(blank=True, choices=[('Developpement', 'Developpement'), ('Linux', 'Linux'), ('Windows Server', 'Windows Server')], default='Developpement', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=1000, verbose_name='Titre'),
        ),
    ]
