# Generated by Django 4.1.3 on 2022-11-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
