# Generated by Django 4.1.1 on 2022-11-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('doctorat', 'Doctorat'), ('master', 'Master'), ('bts', 'BTS'), ('licence', 'Licence'), ('autre', 'Autre')], null=True, verbose_name='Grade'),
        ),
    ]
