# Generated by Django 4.1.1 on 2022-11-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('autre', 'Autre'), ('master', 'Master'), ('licence', 'Licence'), ('doctorat', 'Doctorat'), ('bts', 'BTS')], null=True, verbose_name='Grade'),
        ),
    ]
