# Generated by Django 4.1.3 on 2022-11-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('licence', 'Licence'), ('doctorat', 'Doctorat'), ('bts', 'BTS'), ('master', 'Master'), ('autre', 'Autre')], null=True, verbose_name='Grade'),
        ),
    ]
